package tools.mikey.runescape

data class ItemDefinition(
        var inventoryModel: Int = 0,
        var name: String = "",
        var description: String = "",
        var modelZoom: Int = 0,
        var pitch: Int = 0,
        var roll: Int = 0,
        var translateX: Int = 0,
        var translateY: Int = 0,
        var stackable: Boolean = false,
        var value: Int = 0,
        var requiresMembership: Boolean = false,
        var maleEquipMain: Int = 0,
        var maleEquipTranslateY: Int = 0,
        var maleEquipAttachment: Int = 0,
        var femaleEquipMain: Int = 0,
        var femaleEquipTranslateY: Int = 0,
        var femaleEquipAttachment: Int = 0,
        var tradable: Boolean = false,
        var maleEquipEmblem: Int = 0,
        var femaleEquipEmblem: Int = 0,
        var maleDialogueHead: Int = 0,
        var femaleDialogueHead: Int = 0,
        var maleDialogueHeadgear: Int = 0,
        var femaleDialogueHeadgear: Int = 0,
        var yaw: Int = 0,
        var unNotedId: Int = 0,
        var notedId: Int = 0,
        var modelScaleX: Int = 0,
        var modelScaleY: Int = 0,
        var modelScaleZ: Int = 0,
        var ambient: Int = 0,
        var contrast: Int = 0,
        var teamId: Int = 0,
        var boughtId: Int = 0,
        var boughtTemplateId: Int = 0,
        var placeholderId: Int = 0,
        var placeholderTemplateId: Int = 0,
        var sceneActions: ArrayList<String?> = ArrayList(),
        var widgetActions: ArrayList<String?> = ArrayList(),
        var srcColor: ArrayList<Int> = ArrayList(),
        var destColor: ArrayList<Int> = ArrayList(),
        var srcTexture: ArrayList<Int> = ArrayList(),
        var destTexture: ArrayList<Int> = ArrayList(),
        var stackVariantId: ArrayList<Int> = ArrayList(),
        var stackVariantSize: ArrayList<Int> = ArrayList()
)

